# Generated by Django 6.0 on 2025-12-13 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('name', 'creator'), 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_teams', to=settings.AUTH_USER_MODEL, verbose_name='Создатель команды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание команды'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='Название команды'),
            preserve_default=False,
        ),
    ]
