# Generated by Django 6.0 on 2025-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithemail',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Доступ к админ-панели'),
        ),
    ]
