# Generated by Django 6.0 on 2025-12-14 07:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userwithemail_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithemail',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[users.models.validate_not_future_date, users.models.validate_minimum_age], verbose_name='Дата рождения'),
        ),
    ]
