# Generated by Django 6.0 on 2026-01-09 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Тема встречи')),
                ('date', models.DateField(verbose_name='Дата встречи')),
                ('start_time', models.TimeField(verbose_name='Время начала встречи')),
                ('end_time', models.TimeField(verbose_name='Время окончания встречи')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Создатель встречи')),
                ('members', models.ManyToManyField(related_name='meeting_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники встречи')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['creator', 'date'],
            },
        ),
    ]
