# Generated by Django 6.0 on 2026-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="reminder_1hour_sent",
            field=models.BooleanField(
                default=False, verbose_name="Напоминание за час отправлено"
            ),
        ),
    ]
