# Generated by Django 6.0 on 2026-01-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="overdue_reminder_last_sent",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Дата последнего напоминания о проcрочке",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_1day_sent",
            field=models.BooleanField(
                default=False, verbose_name="Напоминание за 1 день отправлено"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_7days_sent",
            field=models.BooleanField(
                default=False, verbose_name="Напоминание за 7 дней отправлено"
            ),
        ),
    ]
